### ISSUE TITLE
How to run test suite locally?

### ISSUE THREAD

**Issue by drnic** [pay-rails/pay#197]
From `.github/workflows/ci.yml` I think I should be able to run the test suite locally with:

```
STRIPE_PRIVATE_KEY=private RAILS_ENV=test bundle exec rails db:test:prepare test
```

But all the tests fail with:

```
Error:
Pay::Subscription::BraintreeTest#test_braintree_cancel:
NoMethodError: super: no superclass method `processor=' for #<User:0x00007fd5c5401468>
    activemodel (6.0.3.2) lib/active_model/attribute_methods.rb:429:in `method_missing'
    /Users/drnic/Projects/2RK/bosh-sports/pay/lib/pay/billable.rb:32:in `processor='
    /Users/drnic/Projects/2RK/bosh-sports/pay/test/models/braintree_test.rb:6:in `block in <class:BraintreeTest>'
    activesupport (6.0.3.2) lib/active_support/callbacks.rb:428:in `instance_exec'
    activesupport (6.0.3.2) lib/active_support/callbacks.rb:428:in `block in make_lambda'
    activesupport (6.0.3.2) lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
    activesupport (6.0.3.2) lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
```

**Comment by grk** [comment]
I'm also running into this issue, would like to contribute but the local test suite not working is a blocker.

**Comment by excid3** [comment]
In our CI script, we're just doing:

```bash
bin/rails db:test:prepare
bin/rails test
```

Is that not working for you?

**Comment by grk** [comment]
Strange. Somehow, something I ran before modified db schema in a way that made tests fail. Now the above code works. Thanks!

**Comment by excid3** [comment]
I'm going to close this, but feel free to reopen if you can replicate it. I cleared my DB file and it worked just fine and CI works, so I think it's okay.
