### ISSUE TITLE
Paddle subscription webhook issue (NoMethodError Pay::Webhooks::PaddleController#create)

### ISSUE THREAD

**Issue by Ruk33** [pay-rails/pay#252]
Hello, I'm using the Paddle integration for managing the subscriptions on my website. Using the fork (https://github.com/nm/pay/tree/paddle) it works just fine:

Gemfile:
```
gem 'pay', git: 'https://github.com/nm/pay.git', branch: 'paddle'
gem 'paddle_pay', '~> 0.0.1'
```

But, if I update to the latest pay version, I'm getting the following error when a user subscribes (it fails on the webhook):

```
NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x0000557b6c27d2c8>
  from activerecord (6.0.3.4) lib/active_record/store.rb:217:in `store_accessor_for'
  from activerecord (6.0.3.4) lib/active_record/store.rb:212:in `write_store_attribute'
  from activerecord (6.0.3.4) lib/active_record/store.rb:136:in `block (3 levels) in store_accessor'
  from pay (2.3.1) lib/pay/paddle/webhooks/subscription_created.rb:30:in `initialize'
  from pay (2.3.1) app/controllers/pay/webhooks/paddle_controller.rb:13:in `new'
  from pay (2.3.1) app/controllers/pay/webhooks/paddle_controller.rb:13:in `create'
  from actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from actionpack (6.0.3.4) lib/abstract_controller/base.rb:195:in `process_action'
  from actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
  from actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
  from sentry-raven (3.1.1) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:121:in `instance_exec'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:139:in `run_callbacks'
  from actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
  from actionpack (6.0.3.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
  from actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  from activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `block in instrument'
  from activesupport (6.0.3.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `instrument'
  from actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  from actionpack (6.0.3.4) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  from activerecord (6.0.3.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  from actionpack (6.0.3.4) lib/abstract_controller/base.rb:136:in `process'
  from actionview (6.0.3.4) lib/action_view/rendering.rb:39:in `process'
  from actionpack (6.0.3.4) lib/action_controller/metal.rb:190:in `dispatch'
  from actionpack (6.0.3.4) lib/action_controller/metal.rb:254:in `dispatch'
  from actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  from actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
  from actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
  from actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
  from railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
  from railties (6.0.3.4) lib/rails/railtie.rb:190:in `public_send'
  from railties (6.0.3.4) lib/rails/railtie.rb:190:in `method_missing'
  from actionpack (6.0.3.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
  from actionpack (6.0.3.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
  from actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
  from actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
  from rack-attack (6.2.2) lib/rack/attack.rb:156:in `call'
  from rack-attack (6.2.2) lib/rack/attack.rb:170:in `call'
  from warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
  from warden (1.2.9) lib/warden/manager.rb:34:in `catch'
  from warden (1.2.9) lib/warden/manager.rb:34:in `call'
  from rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
  from rack (2.2.3) lib/rack/etag.rb:27:in `call'
  from rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
  from rack (2.2.3) lib/rack/head.rb:12:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:648:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from activesupport (6.0.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from railties (6.0.3.4) lib/rails/rack/logger.rb:37:in `call_app'
  from railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `block in call'
  from activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
  from activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:28:in `tagged'
  from activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `tagged'
  from railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
  from rack (2.2.3) lib/rack/method_override.rb:24:in `call'
  from rack (2.2.3) lib/rack/runtime.rb:22:in `call'
  from activesupport (6.0.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
  from rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/ssl.rb:74:in `call'
  from actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
  from secure_headers (6.3.1) lib/secure_headers/middleware.rb:11:in `call'
  from sentry-raven (3.1.1) lib/raven/integrations/rack.rb:51:in `call'
  from railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
  from puma (4.3.7) lib/puma/configuration.rb:228:in `call'
  from puma (4.3.7) lib/puma/server.rb:713:in `handle_request'
  from puma (4.3.7) lib/puma/server.rb:472:in `process_client'
  from puma (4.3.7) lib/puma/server.rb:328:in `block in run'
  from puma (4.3.7) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

Regards.

**Comment by excid3** [comment]
What database are you using

**Comment by excid3** [comment]
And actually, have you run the latest migrations? We've added a `data` column to subscriptions to store things like the `update_url` and `cancel_url` for Paddle. That might be what's missing.

**Comment by Ruk33** [comment]
Hello @excid3 I'm using PostgreSQL. My migrations run on every deploy so it should be up to date. What's weird is that again, using the paddle branch from the fork it works just fine but will give it another try checking on the migrations. Thanks!

**Comment by excid3** [comment]
Thanks @Ruk33 👍

Can you post your db/schema.rb (just the pay_ tables). It seems like your data column isn't the right type for some reason.

**Comment by Ruk33** [comment]
Hello @excid3 , I just updated to the latest version just to make sure. The error still persist.

Gem versions:

```
paddle_pay 0.0.1
pay 2.4.0
```

This is my schema:

```
  create_table "pay_charges", id: :serial, force: :cascade do |t|
    t.string "owner_type"
    t.integer "owner_id"
    t.string "processor", null: false
    t.string "processor_id", null: false
    t.integer "amount", null: false
    t.integer "amount_refunded"
    t.string "card_type"
    t.string "card_last4"
    t.string "card_exp_month"
    t.string "card_exp_year"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string "receipt_url"
  end

  create_table "pay_subscriptions", id: :serial, force: :cascade do |t|
    t.string "owner_type"
    t.integer "owner_id"
    t.string "name", null: false
    t.string "processor", null: false
    t.string "processor_id", null: false
    t.string "processor_plan", null: false
    t.integer "quantity", default: 1, null: false
    t.datetime "trial_ends_at"
    t.datetime "ends_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string "status"
    t.string "update_url"
    t.string "cancel_url"
  end

  create_table "payments", force: :cascade do |t|
    t.string "payment_type"
    t.integer "billed_cents", default: 0, null: false
    t.string "billed_currency", default: "USD", null: false
    t.datetime "valid_until"
    t.bigint "user_id", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["user_id"], name: "index_payments_on_user_id"
  end
```

```
NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x00005602d797a880>
  from activerecord (6.0.3.2) lib/active_record/store.rb:217:in `store_accessor_for'
  from activerecord (6.0.3.2) lib/active_record/store.rb:212:in `write_store_attribute'
  from activerecord (6.0.3.2) lib/active_record/store.rb:136:in `block (3 levels) in store_accessor'
  from activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:50:in `public_send'
  from activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:50:in `_assign_attribute'
  from activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:43:in `block in _assign_attributes'
  from activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:42:in `each'
  from activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:42:in `_assign_attributes'
  from activerecord (6.0.3.2) lib/active_record/attribute_assignment.rb:21:in `_assign_attributes'
  from activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
  from activerecord (6.0.3.2) lib/active_record/persistence.rb:620:in `block in update'
  from activerecord (6.0.3.2) lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
  from activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
  from activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
  from activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  from activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
  from activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  from activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
  from activesupport (6.0.3.2) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  from activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
  from activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
  from activerecord (6.0.3.2) lib/active_record/transactions.rb:212:in `transaction'
  from activerecord (6.0.3.2) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
  from activerecord (6.0.3.2) lib/active_record/persistence.rb:619:in `update'
  from pay (2.4.0) lib/pay/paddle/webhooks/subscription_payment_succeeded.rb:29:in `create_charge'
  from pay (2.4.0) lib/pay/paddle/webhooks/subscription_payment_succeeded.rb:10:in `initialize'
  from pay (2.4.0) app/controllers/pay/webhooks/paddle_controller.rb:19:in `new'
  from pay (2.4.0) app/controllers/pay/webhooks/paddle_controller.rb:19:in `create'
  from actionpack (6.0.3.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from actionpack (6.0.3.2) lib/abstract_controller/base.rb:195:in `process_action'
  from actionpack (6.0.3.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
  from actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  from activesupport (6.0.3.2) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
  from sentry-raven (3.1.1) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from activesupport (6.0.3.2) lib/active_support/callbacks.rb:121:in `instance_exec'
  from activesupport (6.0.3.2) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  from activesupport (6.0.3.2) lib/active_support/callbacks.rb:139:in `run_callbacks'
  from actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
  from actionpack (6.0.3.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
  from actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  from activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `block in instrument'
  from activesupport (6.0.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `instrument'
  from actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  from actionpack (6.0.3.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  from activerecord (6.0.3.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  from actionpack (6.0.3.2) lib/abstract_controller/base.rb:136:in `process'
  from actionview (6.0.3.2) lib/action_view/rendering.rb:39:in `process'
  from actionpack (6.0.3.2) lib/action_controller/metal.rb:190:in `dispatch'
  from actionpack (6.0.3.2) lib/action_controller/metal.rb:254:in `dispatch'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:834:in `call'
  from railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
  from railties (6.0.3.2) lib/rails/railtie.rb:190:in `public_send'
  from railties (6.0.3.2) lib/rails/railtie.rb:190:in `method_missing'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:834:in `call'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
  from rack-attack (6.2.2) lib/rack/attack.rb:156:in `call'
  from rack-attack (6.2.2) lib/rack/attack.rb:170:in `call'
  from warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
  from warden (1.2.8) lib/warden/manager.rb:34:in `catch'
  from warden (1.2.8) lib/warden/manager.rb:34:in `call'
  from rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
  from rack (2.2.3) lib/rack/etag.rb:27:in `call'
  from rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
  from rack (2.2.3) lib/rack/head.rb:12:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
  from railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
  from activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
  from activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
  from activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
  from railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
  from rack (2.2.3) lib/rack/method_override.rb:24:in `call'
  from rack (2.2.3) lib/rack/runtime.rb:22:in `call'
  from activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
  from rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/ssl.rb:74:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
  from secure_headers (6.3.1) lib/secure_headers/middleware.rb:11:in `call'
  from sentry-raven (3.1.1) lib/raven/integrations/rack.rb:51:in `call'
  from railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
  from puma (4.3.5) lib/puma/configuration.rb:228:in `call'
  from puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
  from puma (4.3.5) lib/puma/server.rb:472:in `process_client'
  from puma (4.3.5) lib/puma/server.rb:328:in `block in run'
  from puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

```
NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x00005602d797a880>
  from activerecord (6.0.3.2) lib/active_record/store.rb:217:in `store_accessor_for'
  from activerecord (6.0.3.2) lib/active_record/store.rb:212:in `write_store_attribute'
  from activerecord (6.0.3.2) lib/active_record/store.rb:136:in `block (3 levels) in store_accessor'
  from pay (2.4.0) lib/pay/paddle/webhooks/subscription_created.rb:30:in `initialize'
  from pay (2.4.0) app/controllers/pay/webhooks/paddle_controller.rb:13:in `new'
  from pay (2.4.0) app/controllers/pay/webhooks/paddle_controller.rb:13:in `create'
  from actionpack (6.0.3.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from actionpack (6.0.3.2) lib/abstract_controller/base.rb:195:in `process_action'
  from actionpack (6.0.3.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
  from actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  from activesupport (6.0.3.2) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
  from sentry-raven (3.1.1) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from activesupport (6.0.3.2) lib/active_support/callbacks.rb:121:in `instance_exec'
  from activesupport (6.0.3.2) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  from activesupport (6.0.3.2) lib/active_support/callbacks.rb:139:in `run_callbacks'
  from actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
  from actionpack (6.0.3.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
  from actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  from activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `block in instrument'
  from activesupport (6.0.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `instrument'
  from actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  from actionpack (6.0.3.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  from activerecord (6.0.3.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  from actionpack (6.0.3.2) lib/abstract_controller/base.rb:136:in `process'
  from actionview (6.0.3.2) lib/action_view/rendering.rb:39:in `process'
  from actionpack (6.0.3.2) lib/action_controller/metal.rb:190:in `dispatch'
  from actionpack (6.0.3.2) lib/action_controller/metal.rb:254:in `dispatch'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:834:in `call'
  from railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
  from railties (6.0.3.2) lib/rails/railtie.rb:190:in `public_send'
  from railties (6.0.3.2) lib/rails/railtie.rb:190:in `method_missing'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:834:in `call'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
  from omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
  from rack-attack (6.2.2) lib/rack/attack.rb:156:in `call'
  from rack-attack (6.2.2) lib/rack/attack.rb:170:in `call'
  from warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
  from warden (1.2.8) lib/warden/manager.rb:34:in `catch'
  from warden (1.2.8) lib/warden/manager.rb:34:in `call'
  from rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
  from rack (2.2.3) lib/rack/etag.rb:27:in `call'
  from rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
  from rack (2.2.3) lib/rack/head.rb:12:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
  from rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
  from railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
  from activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
  from activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
  from activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
  from railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
  from rack (2.2.3) lib/rack/method_override.rb:24:in `call'
  from rack (2.2.3) lib/rack/runtime.rb:22:in `call'
  from activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
  from rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/ssl.rb:74:in `call'
  from actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
  from secure_headers (6.3.1) lib/secure_headers/middleware.rb:11:in `call'
  from sentry-raven (3.1.1) lib/raven/integrations/rack.rb:51:in `call'
  from railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
  from puma (4.3.5) lib/puma/configuration.rb:228:in `call'
  from puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
  from puma (4.3.5) lib/puma/server.rb:472:in `process_client'
  from puma (4.3.5) lib/puma/server.rb:328:in `block in run'
  from puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

Thanks.

**Comment by excid3** [comment]
@Ruk33 Thanks for this.

According to your db schema, you are missing the `data` columns like I mentioned. This is the new migration you're missing: 

https://github.com/pay-rails/pay/blob/master/db/migrate/20200603134434_add_data_to_pay_models.rb

You should run `rails pay:install:migrations` to add the new migrations and then `rails db:migrate`
