### ISSUE TITLE
Getting NoMethodError (undefined method `sync_card_from_stripe')

### ISSUE THREAD

**Issue by ryanfb** [pay-rails/pay#279]
I've followed the various setup instructions (including stopping Spring), and everything else seems to work for establishing a subscription with Stripe Checkout, but for one of the webhook callbacks I get a 500 error:

```
NoMethodError (undefined method `sync_card_from_stripe' for #<User:0x00007f81a7741078>
Did you mean?  sync_email_with_processor):

activemodel (6.1.3) lib/active_model/attribute_methods.rb:469:in `method_missing'
pay (2.6.1) lib/pay/stripe/webhooks/payment_method_updated.rb:12:in `call'
pay (2.6.1) lib/pay/webhooks/delegator.rb:46:in `call'
activesupport (6.1.3) lib/active_support/notifications/fanout.rb:186:in `finish'
activesupport (6.1.3) lib/active_support/notifications/fanout.rb:63:in `block in finish'
activesupport (6.1.3) lib/active_support/notifications/fanout.rb:63:in `each'
activesupport (6.1.3) lib/active_support/notifications/fanout.rb:63:in `finish'
activesupport (6.1.3) lib/active_support/notifications/instrumenter.rb:45:in `finish_with_state'
activesupport (6.1.3) lib/active_support/notifications/instrumenter.rb:30:in `instrument'
activesupport (6.1.3) lib/active_support/notifications.rb:203:in `instrument'
pay (2.6.1) lib/pay/webhooks/delegator.rb:35:in `instrument'
pay (2.6.1) lib/pay/webhooks.rb:6:in `instrument'
pay (2.6.1) app/controllers/pay/webhooks/stripe_controller.rb:19:in `delegate_event'
pay (2.6.1) app/controllers/pay/webhooks/stripe_controller.rb:9:in `create'
actionpack (6.1.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.3) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.1.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.1.3) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
actiontext (6.1.3) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (6.1.3) lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
activesupport (6.1.3) lib/active_support/callbacks.rb:126:in `instance_exec'
activesupport (6.1.3) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
activesupport (6.1.3) lib/active_support/callbacks.rb:137:in `run_callbacks'
actionpack (6.1.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.1.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.1.3) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (6.1.3) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.3) lib/active_support/notifications.rb:203:in `instrument'
actionpack (6.1.3) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
actionpack (6.1.3) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
activerecord (6.1.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.1.3) lib/abstract_controller/base.rb:165:in `process'
actionview (6.1.3) lib/action_view/rendering.rb:39:in `process'
actionpack (6.1.3) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.1.3) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.1.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.1.3) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.1.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.3) lib/action_dispatch/routing/route_set.rb:842:in `call'
```

I have `include Pay::Billable` on my `User` model, it seems like for whatever reason the expected `Pay::Stripe::Billable` methods aren't defined on instances of it although they're expected by the caller to be there. Some poking around leads me to believe that maybe `billable.sync_card_from_stripe` should instead be `billable.payment_processor.sync_card_from_stripe` in these locations:

* https://github.com/pay-rails/pay/blob/v2.6.1/lib/pay/stripe/webhooks/customer_updated.rb#L12
* https://github.com/pay-rails/pay/blob/v2.6.1/lib/pay/stripe/webhooks/payment_method_updated.rb#L12

**Comment by excid3** [comment]
Thanks @ryanfb 👍  This should be fixed now.

I'm going to further improve those tests so they don't stub that method.
