### ISSUE TITLE
Pay::Subscription and Pay::Charge records not saved in Database sometimes.

### ISSUE THREAD

**Issue by rohitbansal0689** [pay-rails/pay#382]
While working in a local environment. Sometimes, I have seen subscription is added successfully in stripe but pay doesn't create a corresponding subscription and charge in respective tables. 

```
  def show
    current_user.processor = :stripe
    current_user.customer

    @checkout_session = current_user.payment_processor.checkout(mode: "subscription", line_items: "plan_FxvZ6ZvDblKLQW")
  end
```

Checkout button successfully renders to the stripe checkout page but I can see the 404 error in JS console `https://api.stripe.com/v1/consumers/sessions/create`

Entering the card details and hit the subscribe button successfully added the subscription in stripe **but fails to add the records in Database.** 

Here is the logs, it is unable to find the customer. But subscription is added successfully in stripe to the right customer

```
2021-07-28 17:39:54 [200] POST /v1/checkout/sessions [req_glADzBHDBtfOgn]
2021-07-28 17:39:53 [200] POST /v1/customers [req_DTo9eRkx880O3R]
2021-07-28 17:39:54 [200] GET /v1/customers/:id [req_7p4QRuhnnBOdwS]
2021-07-28 17:40:06 [200] POST /v1/payment_pages/:id [req_kaxjfiiYzMrxQl]
2021-07-28 17:40:07 [404] POST /v1/consumers/sessions/create [req_wlwgmJtTRhGsut]

Type: invalid_request_error
Message: Could not find Consumer

2021-07-28 17:40:17 [200] GET /v1/customers/:id [req_Rw8LoHbgI2A97B]
2021-07-28 17:41:17 [200] GET /v1/customers/:id [req_SYbOv9P1dloAqp]
2021-07-28 17:42:31 [200] POST /v1/payment_methods [req_avVvW0D5dGcCkj]
2021-07-28 17:42:32 [200] POST /v1/payment_pages/:id/confirm [req_hgHSMMYHo9Cexi]
2021-07-28 17:42:35 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_LPDYqjusyFsKQT]
2021-07-28 17:42:36 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_zN03KTpyEOSDaA]
2021-07-28 17:42:37 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_YDCV2CD9sESJ6x]
2021-07-28 17:42:38 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_MxETgLJyiUz8Yk]
2021-07-28 17:42:39 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_NTWunJY0nwJSqr]
2021-07-28 17:42:40 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_HY5TnHyFLBjDNy]
2021-07-28 17:42:41 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_um711eJ2luHyjT]
2021-07-28 17:42:42 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_p9yBqJf7cmGpAF]
2021-07-28 17:42:42 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_u5swVEdpeSQtQX]
2021-07-28 17:42:43 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_DE7ztqKa0o0LaR]
2021-07-28 17:42:44 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_YgV6BL4pQD9Jaz]
2021-07-28 17:42:45 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_roI7zmVLuQyK6K]
2021-07-28 17:42:55 [200] GET /v1/customers/:id [req_jMd5BBsphCcPTc]
2021-07-28 17:43:33 [200] GET /v1/customers/:id [req_uYV26KH0XL6SjL]
2021-07-28 17:44:38 [200] GET /v1/customers/:id [req_SRRia8BUozPxIh]
2021-07-28 17:45:22 [200] GET /v1/customers/:id [req_Nvzn9P4ltrMSKi]
2021-07-28 17:46:09 [200] GET /v1/customers/:id [req_nag7hZIYXf05Hx]
2021-07-28 17:47:04 [200] GET /v1/customers/:id [req_3Goic2Lee4joxU]
```

**Comment by excid3** [comment]
I don't think a `Consumer` is a documented API resource, so that seems like something internal to Stripe. Not sure what is going on there.

**Comment by rohitbansal0689** [comment]
It is intermittent. I have tried just now, this time logs 

Checkout button successfully renders to the stripe checkout page but still I can see the 404 error in JS console https://api.stripe.com/v1/consumers/sessions/create but not in logs.

Entering the card details and hit the subscribe button successfully added the subscription in stripe but fails to add the records in Database.

```
2021-07-28 19:36:39 [200] POST /v1/customers [req_gto6XnQTQiYm4J]
2021-07-28 19:37:33 [200] POST /v1/payment_methods [req_tZRed3Z8FrXuUl]
2021-07-28 19:37:42 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_Jo89RWJs3UgM2X]
2021-07-28 19:37:44 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_gJuxMnCy8cDhvQ]
2021-07-28 19:37:34 [200] POST /v1/payment_pages/:id/confirm [req_TuOc9NIGOcQYDe]
```

Next I have restarted the rails server and refresh the checkout page and click on checkout button, this time no consumer error but still fail to add  charge and subscription records in Database.

```
2021-07-28 19:41:19 [200] GET /v1/customers/:id [req_vTvO4D4hTVhwb1]
2021-07-28 19:41:39 [200] POST /v1/checkout/sessions [req_WdzWyeQJfqqajI]
2021-07-28 19:41:47 [200] POST /v1/payment_pages/:id [req_BWs1PR4FMNpeIN]
2021-07-28 19:41:38 [200] GET /v1/customers/:id [req_RP4IzV0wKyLNZW]
2021-07-28 19:42:02 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_BZyhOM88xWwfBj]
2021-07-28 19:41:55 [200] POST /v1/payment_pages/:id/confirm [req_P3Ybi633U0VqTc]
2021-07-28 19:42:04 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_zT7tCpIS1nPOlA]
2021-07-28 19:42:07 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_7y9w4G10xIwFum]
2021-07-28 19:42:03 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_KgqIglZd0ABqWj]
2021-07-28 19:42:06 [200] GET /v1/checkout/sessions/completed_webhook_delivered/:id [req_Gjkhuw7mVD6bnQ]
2021-07-28 19:42:05 [200] GET /v1/customers/:id [req_BMo3fLgBxiWlQc]

2021-07-28 19:42:49 [200] GET /v1/customers/:id [req_EDm8tp4gMF5fvL]
```

**Comment by excid3** [comment]
You have to use the Stripe CLI to forward webhooks to Rails for saving them in the database.

**Comment by rohitbansal0689** [comment]
Yeah I have already done that `stripe listen --forward-to localhost:3000/pay/webhooks/stripe` And set the signing_secret already. 

For one of the user it worked absolutely fine, here is the log
```
2021-07-28 16:49:57   --> customer.created [evt_0JIAnoI8eGilJs5V4tixkVuR]
2021-07-28 16:49:57  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAnoI8eGilJs5V4tixkVuR]
2021-07-28 16:50:42   --> charge.succeeded [evt_0JIAoXI8eGilJs5VtDFnATBk]
2021-07-28 16:50:42   --> payment_method.attached [evt_0JIAoYI8eGilJs5VLwfWC7rs]
2021-07-28 16:50:43   --> invoice.created [evt_0JIAoYI8eGilJs5VxmVo6URq]
2021-07-28 16:50:43  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoYI8eGilJs5VxmVo6URq]
2021-07-28 16:50:43   --> invoice.finalized [evt_0JIAoYI8eGilJs5V9E3Qoc0E]
2021-07-28 16:50:43   --> customer.subscription.updated [evt_0JIAoZI8eGilJs5Vx8LZea6o]
2021-07-28 16:50:43   --> customer.subscription.created [evt_0JIAoYI8eGilJs5VnSUzHHgy]
2021-07-28 16:50:43  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoYI8eGilJs5V9E3Qoc0E]
2021-07-28 16:50:43   --> invoice.paid [evt_0JIAoZI8eGilJs5VF8oScBfS]
2021-07-28 16:50:43  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoZI8eGilJs5VF8oScBfS]
2021-07-28 16:50:44   --> invoice.payment_succeeded [evt_0JIAoZI8eGilJs5VxyBudCnZ]
2021-07-28 16:50:44  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoZI8eGilJs5VxyBudCnZ]
2021-07-28 16:50:44   --> invoice.updated [evt_0JIAoYI8eGilJs5VS34GhG69]
2021-07-28 16:50:44  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoYI8eGilJs5VS34GhG69]
2021-07-28 16:50:44   --> checkout.session.completed [evt_0JIAoXI8eGilJs5VFIlFS28y]
2021-07-28 16:50:44   --> invoice.updated [evt_0JIAoZI8eGilJs5VhVYnDYNH]
2021-07-28 16:50:44  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoZI8eGilJs5VhVYnDYNH]
2021-07-28 16:50:44   --> payment_intent.succeeded [evt_0JIAoaI8eGilJs5VEUacmczw]
2021-07-28 16:50:44   --> payment_intent.created [evt_0JIAoaI8eGilJs5VZdPVXMbN]
2021-07-28 16:50:44  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoaI8eGilJs5VZdPVXMbN]
2021-07-28 16:50:44  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoYI8eGilJs5VLwfWC7rs]
2021-07-28 16:50:45  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoYI8eGilJs5VnSUzHHgy]
2021-07-28 16:50:46  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoZI8eGilJs5Vx8LZea6o]
2021-07-28 16:50:46  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoXI8eGilJs5VtDFnATBk]
2021-07-28 16:50:46  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoXI8eGilJs5VFIlFS28y]
2021-07-28 16:50:47  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIAoaI8eGilJs5VEUacmczw]
```

**Comment by rohitbansal0689** [comment]
I have again enter stripe listen --forward-to localhost:3000/pay/webhooks/stripe
`> Ready! Your webhook signing secret is xxxxxxxxxxxxxxxxxxxxxxxxxxx (^C to quit)
`

This time I have created new user -> Go to checkout -> Stripe checkout page -> Enter card details -> Subscribe

It created 2  charge records and 3 subscription records in DB  but on stripe side it is fine.

```
2021-07-28 19:56:50   --> customer.created [evt_0JIDigI8eGilJs5Ve53ghbit]
2021-07-28 19:56:51  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDigI8eGilJs5Ve53ghbit]
2021-07-28 19:57:36   --> charge.succeeded [evt_0JIDjQI8eGilJs5VvNHec7JE]
2021-07-28 19:57:37   --> checkout.session.completed [evt_0JIDjQI8eGilJs5VfKDkjgw1]
2021-07-28 19:57:37   --> payment_method.attached [evt_0JIDjQI8eGilJs5VY8tJcx4Q]
2021-07-28 19:57:37   --> invoice.created [evt_0JIDjQI8eGilJs5VJBXeZRYP]
2021-07-28 19:57:37  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjQI8eGilJs5VJBXeZRYP]
2021-07-28 19:57:38   --> customer.subscription.created [evt_0JIDjQI8eGilJs5V1YYXNN0f]
2021-07-28 19:57:38   --> customer.subscription.updated [evt_0JIDjRI8eGilJs5VuqCxLtoc]
2021-07-28 19:57:38   --> invoice.updated [evt_0JIDjRI8eGilJs5VIBYFnc5M]
2021-07-28 19:57:38   --> invoice.paid [evt_0JIDjRI8eGilJs5VeEpHn4TK]
2021-07-28 19:57:38  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjRI8eGilJs5VIBYFnc5M]
2021-07-28 19:57:38  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjRI8eGilJs5VeEpHn4TK]
2021-07-28 19:57:38   --> invoice.payment_succeeded [evt_0JIDjRI8eGilJs5V28tEyrXB]
2021-07-28 19:57:38  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjRI8eGilJs5V28tEyrXB]
2021-07-28 19:57:38   --> payment_intent.succeeded [evt_0JIDjSI8eGilJs5V6zXsqEe8]
2021-07-28 19:57:38   --> invoice.updated [evt_0JIDjSI8eGilJs5VTakStgQB]
2021-07-28 19:57:38  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjSI8eGilJs5VTakStgQB]
2021-07-28 19:57:38   --> payment_intent.created [evt_0JIDjSI8eGilJs5VYoroLXml]
2021-07-28 19:57:38  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjSI8eGilJs5VYoroLXml]
2021-07-28 19:57:38  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjQI8eGilJs5VY8tJcx4Q]
2021-07-28 19:57:39  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjQI8eGilJs5V1YYXNN0f]
2021-07-28 19:57:39  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjRI8eGilJs5VuqCxLtoc]
2021-07-28 19:57:39  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjQI8eGilJs5VfKDkjgw1]
2021-07-28 19:57:40  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjQI8eGilJs5VvNHec7JE]
2021-07-28 19:57:40  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_0JIDjSI8eGilJs5V6zXsqEe8]
```

**Comment by excid3** [comment]
Yeah, master has a fix for handling the race conditions since Stripe sends over several duplicate events.

**Comment by rohitbansal0689** [comment]
Default is master branch I guess. Yeah??
Your recent condition will fix this duplicate issues. Any idea when records are not created in DB ?? 

It's like I have to quit  console and then listen the web-hook again.   `stripe listen --forward-to localhost:3000/pay/webhooks/stripe`

**Comment by rohitbansal0689** [comment]
Master fix the duplicate issue. Thank you.  

But still I can see the 404 error in JS console https://api.stripe.com/v1/consumers/sessions/create for successful cases.

**Comment by excid3** [comment]
That's not a request that Pay makes, so not sure what to tell you there. Might need to contact Stripe support about it.

**Comment by excid3** [comment]
I am not sure. I've noticed that if I restart my Rails server, sometimes Stripe CLI needs restarting too. That may be a bug in their CLI or something.

**Comment by rohitbansal0689** [comment]
yeah, but the could be local behaviour I guess. I hope production won't replicate this.

Thank you!!

**Comment by excid3** [comment]
The Stripe CLI isn't used in production, so it isn't a problem. 👍

**Comment by rohitbansal0689** [comment]
Exactly. Thank you!!

**Comment by rohitbansal0689** [comment]
It still add duplicates. 1092 is the latest one.

irb(main):020:0> Pay::Subscription.pluck(:owner_id)
   (0.3ms)  SELECT "pay_subscriptions"."owner_id" FROM "pay_subscriptions"
=> [1084, 1084, 1085, 1089, 1089, 1089, 1090, 1092, 1092, 1092]

irb(main):021:0> Pay::Charge.pluck(:owner_id)
   (0.4ms)  SELECT "pay_charges"."owner_id" FROM "pay_charges" ORDER BY "pay_charges"."created_at" DESC
=> [1092, 1092, 1090, 1089, 1089, 1085, 1084, 1084]

**Comment by excid3** [comment]
I'm also working on this which is related: https://github.com/pay-rails/pay/pull/383

**Comment by rohitbansal0689** [comment]
Ahhh when it will be going to release?

**Comment by excid3** [comment]
Not sure yet, but you can update your gemfile to use that branch and test it.

**Comment by rohitbansal0689** [comment]
I have already done that. But still same for me!!

**Comment by rohitbansal0689** [comment]
Talked to the stripe support. Shared screenshot, logs.  They checked everything and stated that the following. 

```
I think the issue may be stemming from the endpoint that the error is returning on; v1/consumers/sessions/create

This isn't a valid Stripe endpoint. We don't have "consumers" as an endpoint, we use "customers"
```

I hope this is something else https://github.com/pay-rails/pay/search?q=consumer&type=

**Comment by excid3** [comment]
That search only returns an ActionCable line which is unrelated.

We don't have any code that hits that endpoint, so not sure where that's coming from.

**Comment by rohitbansal0689** [comment]
Ok. They have also denied the same endpoint and consumer is not present in anywhere  in my code.

**Comment by rohitbansal0689** [comment]
I was trying to create the charge from rails console

user = User.find_by(email: 'testwebhook@gmail.com')
user.processor = 'stripe'
user.charge(1500)

Charge is created successfully in table. I can see the Post webhook event with params but also this error

```
  ↳ /Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/stripe/charge.rb:36
   (0.8ms)  COMMIT
  ↳ /Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/stripe/charge.rb:35
Completed 500 Internal Server Error in 1227ms (ActiveRecord: 2.4ms)


Not notifying due to notify_release_stages :["production", "qa"]
  
NoMethodError (undefined method `owner' for true:TrueClass):
```

**Comment by excid3** [comment]
You'll have to share the full stacktrace.

**Comment by rohitbansal0689** [comment]
Rails console:

```
irb(main):164:0> user.card_token = 'pm_0JIcIbI8eGilJs5VU302nk4B'
=> "pm_0JIcIbI8eGilJs5VU302nk4B"
irb(main):165:0> user.charge(1000)
   (0.2ms)  BEGIN
   (0.2ms)  COMMIT
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."processor" = $1 AND "users"."processor_id" = $2 LIMIT $3  [["processor", "stripe"], ["processor_id", "cus_JwVHJfUPRdLsiK"], ["LIMIT", 1]]
  Pay::Charge Load (0.2ms)  SELECT  "pay_charges".* FROM "pay_charges" WHERE "pay_charges"."owner_id" = $1 AND "pay_charges"."owner_type" = $2 AND "pay_charges"."processor" = $3 AND "pay_charges"."processor_id" = $4 ORDER BY "pay_charges"."created_at" DESC LIMIT $5  [["owner_id", 1132], ["owner_type", "User"], ["processor", "stripe"], ["processor_id", "ch_0JIcsSI8eGilJs5V88OOpgu4"], ["LIMIT", 1]]
   (0.1ms)  BEGIN
  Pay::Charge Exists (0.2ms)  SELECT  1 AS one FROM "pay_charges" WHERE LOWER("pay_charges"."processor_id") = LOWER($1) AND "pay_charges"."processor" = $2 LIMIT $3  [["processor_id", "ch_0JIcsSI8eGilJs5V88OOpgu4"], ["processor", "stripe"], ["LIMIT", 1]]
  Pay::Charge Create (0.2ms)  INSERT INTO "pay_charges" ("owner_type", "owner_id", "processor", "processor_id", "amount", "amount_refunded", "card_type", "card_last4", "card_exp_month", "card_exp_year", "created_at", "updated_at", "data", "currency") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING "id"  [["owner_type", "User"], ["owner_id", 1132], ["processor", "stripe"], ["processor_id", "ch_0JIcsSI8eGilJs5V88OOpgu4"], ["amount", 1000], ["amount_refunded", 0], ["card_type", "visa"], ["card_last4", "4242"], ["card_exp_month", "2"], ["card_exp_year", "2023"], ["created_at", "2021-07-29 17:18:36"], ["updated_at", "2021-07-29 17:18:37.271273"], ["data", "{}"], ["currency", "usd"]]
   (0.4ms)  COMMIT
=> #<Pay::Charge id: 35, owner_type: "User", owner_id: 1132, processor: "stripe", processor_id: "ch_0JIcsSI8eGilJs5V88OOpgu4", amount: 1000, amount_refunded: 0, card_type: "visa", card_last4: "4242", card_exp_month: "2", card_exp_year: "2023", created_at: "2021-07-29 17:18:36", updated_at: "2021-07-29 17:18:37", data: {}, currency: "usd", application_fee_amount: nil, pay_subscription_id: nil>
irb(main):166:0> 
```

Development Logs:


```
User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."processor" = $1 AND "users"."processor_id" = $2 LIMIT $3  [["processor", "stripe"], ["processor_id", "cus_JwVHJfUPRdLsiK"], ["LIMIT", 1]]
  ↳ /Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay.rb:93
  Pay::Charge Load (0.5ms)  SELECT  "pay_charges".* FROM "pay_charges" WHERE "pay_charges"."owner_id" = $1 AND "pay_charges"."owner_type" = $2 AND "pay_charges"."processor" = $3 AND "pay_charges"."processor_id" = $4 ORDER BY "pay_charges"."created_at" DESC LIMIT $5  [["owner_id", 1132], ["owner_type", "User"], ["processor", "stripe"], ["processor_id", "ch_0JIcsSI8eGilJs5V88OOpgu4"], ["LIMIT", 1]]
  ↳ /Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/stripe/charge.rb:34
   (0.1ms)  BEGIN
  ↳ /Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/stripe/charge.rb:35
  Pay::Charge Load (0.3ms)  SELECT  "pay_charges".* FROM "pay_charges" WHERE "pay_charges"."id" = $1 LIMIT $2 FOR UPDATE  [["id", 35], ["LIMIT", 1]]
  ↳ /Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/stripe/charge.rb:35
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1132], ["LIMIT", 1]]
  ↳ /Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/stripe/charge.rb:36
  Pay::Charge Exists (0.2ms)  SELECT  1 AS one FROM "pay_charges" WHERE LOWER("pay_charges"."processor_id") = LOWER($1) AND "pay_charges"."id" != $2 AND "pay_charges"."processor" = $3 LIMIT $4  [["processor_id", "ch_0JIcsSI8eGilJs5V88OOpgu4"], ["id", 35], ["processor", "stripe"], ["LIMIT", 1]]
  ↳ /Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/stripe/charge.rb:36
   (0.8ms)  COMMIT
  ↳ /Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/stripe/charge.rb:35
Completed 500 Internal Server Error in 1272ms (ActiveRecord: 2.5ms)


Not notifying due to notify_release_stages :["production", "qa"]
  
NoMethodError (undefined method `owner' for true:TrueClass):
  
/Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/stripe/webhooks/charge_succeeded.rb:7:in `call'
/Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/webhooks/delegator.rb:46:in `call'
activesupport (5.2.3) lib/active_support/notifications/fanout.rb:129:in `finish'
activesupport (5.2.3) lib/active_support/notifications/fanout.rb:48:in `block in finish'
activesupport (5.2.3) lib/active_support/notifications/fanout.rb:48:in `each'
activesupport (5.2.3) lib/active_support/notifications/fanout.rb:48:in `finish'
activesupport (5.2.3) lib/active_support/notifications/instrumenter.rb:44:in `finish_with_state'
activesupport (5.2.3) lib/active_support/notifications/instrumenter.rb:29:in `instrument'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `instrument'
/Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/webhooks/delegator.rb:35:in `instrument'
/Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/lib/pay/webhooks.rb:6:in `instrument'
/Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/app/controllers/pay/webhooks/stripe_controller.rb:19:in `delegate_event'
/Users/rohitbansal/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/pay-263b54eb0a0f/app/controllers/pay/webhooks/stripe_controller.rb:9:in `create'
actionpack (5.2.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.3) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'




```

**Comment by excid3** [comment]
I just pushed a commit to master that should fix that. It was returning the `with_lock` value, but should be the Pay charge or subscription.

**Comment by rohitbansal0689** [comment]
Yeah, it is working now. Thank you.
One more thing. Right now pay send email alerts only for three events I guess. Do I need to override the webhooks lib/pay/stripe/webhooks/{{event_name.rb}}

**Comment by rohitbansal0689** [comment]
Unique constraint is added in table to avoid duplicated. But multiple emails will be sent if charge_succeeded or other web hooks will be triggered by stripe multiple times.

**Comment by excid3** [comment]
Going to close this, but if you get updated to Pay 3 and still have the issue, let me know. 👍

**Comment by rohitbansal0689** [comment]
Sure, Thank you!
