### ISSUE TITLE
Undefined method or variable `pay_customer` for Class

### ISSUE THREAD

**Issue by brian-lai** [pay-rails/pay#415]
```
activerecord-6.0.4/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined local variable or method 'pay_customer' for User (call 'User.connection' to establish a connection):Class (NameError)

```

I'm running into an issue when configuring this gem where this message is popping up.

Is this due to this [commit](https://github.com/pay-rails/pay/commit/cfe9176b97caef0815683b722739e97488aa11b3)?

**Comment by excid3** [comment]
You'll have to share the full stacktrace. Just rolling out Pay v3 today and still fixing some bugs.

**Comment by brian-lai** [comment]
sure thing

```
/Users/brianpersonal/dev/demostripeapp/app/models/user.rb:5:in `<class:User>': uninitialized constant Pay::Customer (NameError)
	from /Users/brianpersonal/dev/demostripeapp/app/models/user.rb:4:in `<main>'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/activesupport-6.0.4/lib/active_support/inflector/methods.rb:282:in `const_get'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/activesupport-6.0.4/lib/active_support/inflector/methods.rb:282:in `block in constantize'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/activesupport-6.0.4/lib/active_support/inflector/methods.rb:280:in `each'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/activesupport-6.0.4/lib/active_support/inflector/methods.rb:280:in `inject'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/activesupport-6.0.4/lib/active_support/inflector/methods.rb:280:in `constantize'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/activesupport-6.0.4/lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise.rb:316:in `get'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise/mapping.rb:83:in `to'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise/mapping.rb:78:in `modules'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise/mapping.rb:95:in `routes'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise/mapping.rb:162:in `default_used_route'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise/mapping.rb:72:in `initialize'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise.rb:346:in `new'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise.rb:346:in `add_mapping'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise/rails/routes.rb:243:in `block in devise_for'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise/rails/routes.rb:242:in `each'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/devise-4.8.0/lib/devise/rails/routes.rb:242:in `devise_for'
	from /Users/brianpersonal/dev/demostripeapp/config/routes.rb:5:in `block in <main>'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/actionpack-6.0.4/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/actionpack-6.0.4/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/actionpack-6.0.4/lib/action_dispatch/routing/route_set.rb:408:in `draw'
	from /Users/brianpersonal/dev/demostripeapp/config/routes.rb:4:in `<main>'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/application/routes_reloader.rb:20:in `reload!'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/application/routes_reloader.rb:29:in `block in updater'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/activesupport-6.0.4/lib/active_support/file_update_checker.rb:83:in `execute'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/application/routes_reloader.rb:10:in `execute'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/initializable.rb:32:in `run'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/railties-6.0.4/lib/rails/application.rb:363:in `initialize!'
	from /Users/brianpersonal/dev/demostripeapp/config/environment.rb:5:in `<main>'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/activesupport-6.0.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/activesupport-6.0.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/activesupport-6.0.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/brianpersonal/.rvm/gems/ruby-2.6.7/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/brianpersonal/.rvm/rubies/ruby-2.6.7/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by excid3** [comment]
What's line 4 of your User.rb file? And you're using `gem "pay", "~> 3.0.0"`?

**Comment by brian-lai** [comment]
line 4 is the `customer_pay` addition to the `User` model

```

class User < ApplicationRecord
  pay_customer
end
```

and nope, i'm not.  It's pegged to `2.0` per the guidelines.
And actually, now that you bring that up it shouldn't be due to that commit 🤔

**Comment by brian-lai** [comment]
oh hold on, this is my mistake.  I'm following the guide from master... 🤦 

i should check out the README for 2.7.2 instead.

I'm happy to test out v3 though if you need a hand

**Comment by excid3** [comment]
That would do it!

And yes, please do test Pay 3. I released it today and it fixes a ton of things in v2.

**Comment by the-anthony-s** [comment]
@excid3 small note, in the installation documentation it says to use: `gem 'pay', '~> 2.0'`, not `gem 'pay', '~> 3.0.0'`

**Comment by excid3** [comment]
@the-anthony-s Thanks for the reminder, that's updated!
