### ISSUE TITLE
Error performing `Pay::Webhooks::ProcessJob`

### ISSUE THREAD

**Issue by gowthamgts** [pay-rails/pay#620]
Hello, I'm using paddle as the payment processor and currently testing the integration via pay gem in my local via ngrok setup. When there's a plan change or a new subscription (the changes are reflected in the database though), I'm seeing the below error every time:

```
[ActiveJob] [Pay::Webhooks::ProcessJob] [78534e1a-0ad0-4da6-8171-26634e77bb98] Error performing Pay::Webhooks::ProcessJob (Job ID: 78534e1a-0ad0-4da6-8171-26634e77bb98) from Async(default) in 3677.68ms: ActiveSupport::Notifications::InstrumentationSubscriberError (Exception(s) occurred within instrumentation subscribers: PaddlePay::PaddlePayError, PaddlePay::PaddlePayError, PaddlePay::PaddlePayError):
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/fanout.rb:101:in `iterate_guarding_exceptions'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/fanout.rb:76:in `finish'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:49:in `finish_with_state'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:30:in `instrument'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `instrument'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pay-3.0.24/lib/pay/webhooks/delegator.rb:35:in `instrument'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pay-3.0.24/lib/pay/webhooks.rb:7:in `instrument'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pay-3.0.24/app/models/pay/webhook.rb:8:in `process!'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pay-3.0.24/lib/pay/webhooks/process_job.rb:5:in `perform'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/execution.rb:59:in `block in _perform_job'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/i18n-1.10.0/lib/i18n.rb:328:in `with_locale'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/execution.rb:58:in `_perform_job'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/instrumentation.rb:20:in `_perform_job'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/execution.rb:46:in `perform_now'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/instrumentation.rb:14:in `block in perform_now'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/instrumentation.rb:25:in `block in instrument'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `instrument'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/instrumentation.rb:35:in `instrument'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/instrumentation.rb:14:in `perform_now'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/logging.rb:18:in `block in perform_now'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/tagged_logging.rb:37:in `tagged'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/tagged_logging.rb:99:in `tagged'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/logging.rb:25:in `tag_logger'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/logging.rb:18:in `perform_now'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/execution.rb:24:in `block in execute'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/reloader.rb:71:in `wrap'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/execution.rb:22:in `execute'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activejob-7.0.2.3/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/Users/gts/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```

Is there something wrong with my setup? Can you please assist or redirect me to the right place? TIA.

**Comment by excid3** [comment]
Please provide some steps to reproduce the issue.

**Comment by gowthamgts** [comment]
Apologies, while writing up the reproduction steps, I came across a typo for paddle secret configuration. the `paddle.environment` was configured as `paddle.environments`.

I fixed this and now it seems to work fine. Thanks for making this gem and apologies for wasting your time. Cheers.
