### ISSUE TITLE
Stripe webhooks return a 404 error

### ISSUE THREAD

**Issue by Tioneb12** [pay-rails/pay#624]
I have set 

```
  config.automount_routes = true
  config.routes_path = "/pay
```

Add event 

listen with stripe cli at :
stripe listen --forward-to localhost:3000/pay/webhooks/stripe

```
stripe listen --forward-to localhost:3000/pay/webhooks/stripe                                                   ✔  15m 30s   2.7.3   14:54:54 
A newer version of the Stripe CLI is available, please update to: v1.8.11
> Ready! You are using Stripe API Version [2020-08-27]. Your webhook signing secret is whsec_f7ad......................................... (^C to quit)
2022-05-07 14:55:54   --> payment_method.attached [evt_1KwnAsBc3iuMhVH4erW2g6P4]
2022-05-07 14:55:54   --> customer.source.created [evt_1KwnAsBc3iuMhVH4JzyrPxyI]
2022-05-07 14:55:54  <--  [400] POST http://localhost:3000/pay/webhooks/stripe [evt_1KwnAsBc3iuMhVH4JzyrPxyI]
2022-05-07 14:55:54  <--  [400] POST http://localhost:3000/pay/webhooks/stripe [evt_1KwnAsBc3iuMhVH4erW2g6P4]
2022-05-07 14:55:54   --> customer.created [evt_1KwnAsBc3iuMhVH4W541NDiS]
2022-05-07 14:55:54  <--  [400] POST http://localhost:3000/pay/webhooks/stripe [evt_1KwnAsBc3iuMhVH4W541NDiS]
2022-05-07 14:55:55   --> plan.created [evt_1KwnAtBc3iuMhVH4K0g2r8cm]
2022-05-07 14:55:55   --> price.created [evt_1KwnAtBc3iuMhVH4iikXeMzu]
2022-05-07 14:55:55  <--  [400] POST http://localhost:3000/pay/webhooks/stripe [evt_1KwnAtBc3iuMhVH4iikXeMzu]
2022-05-07 14:55:55  <--  [400] POST http://localhost:3000/pay/webhooks/stripe [evt_1KwnAtBc3iuMhVH4K0g2r8cm]
2022-05-07 14:55:59   --> charge.succeeded [evt_3KwnAuBc3iuMhVH41QdpbfIm]
2022-05-07 14:55:59   --> customer.updated [evt_1KwnAxBc3iuMhVH4BWqAgpDy]
2022-05-07 14:55:59   --> invoice.created [evt_1KwnAxBc3iuMhVH4BC8aaH4z]
2022-05-07 14:55:59   --> invoice.finalized [evt_1KwnAxBc3iuMhVH4JKJ9Vpom]
2022-05-07 14:55:59   --> invoice.paid [evt_1KwnAxBc3iuMhVH4MMuqlqPg]
......
```

In my rails console :

```
Started POST "/pay/webhooks/stripe" for ::1 at 2022-05-07 15:22:25 +0200
Processing by Pay::Webhooks::StripeController#create as XML
.....
.....
.....
Cannot verify signature without a Stripe signing secret
  /Users/ben/code/Tioneb12/postgis/app/controllers/pay/webhooks/stripe_controller.rb:41:in `secrets'
  /Users/ben/code/Tioneb12/postgis/app/controllers/pay/webhooks/stripe_controller.rb:28:in `verified_event'
  /Users/ben/code/Tioneb12/postgis/app/controllers/pay/webhooks/stripe_controller.rb:9:in `create'
```

How can I add Stripe signin secret localy ?

**Comment by cjilbert504** [comment]
@Tioneb12 - did you set your webhook endpoints in your Stripe developer dashboard, get the signing secret from the endpoint and add it to your credentials file? Just trying to get a better idea of where you're at with the setup.

**Comment by Tioneb12** [comment]
@cjilbert504 Thanks for your help 

In the credentials file, I have set : 

stripe:
  private_key: sk_test.....
  public_key: pk_test.....
  
  But found differents signin_secret :
  whsec_83jy.... on this page https://dashboard.stripe.com/test/webhooks
  whsec_f7ad... with stripe listen --print-secret
  
  I tried the both, but always have the same error error 400 and Cannot verify signature without a Stripe signing secret
