### ISSUE TITLE
Stripe PayPaymentMethod webhook not saving PaymentMethod

### ISSUE THREAD

**Issue by alexanderdavisn** [pay-rails/pay#635]
When receiving a `payment_method.attached` webhook event, the process to create the PayPaymentMethod fails due to:

> Error performing Pay::Webhooks::ProcessJob (Job ID: f88fd1ea-713a-45dd-8112-e01e419669c6) from Sidekiq(default) in 96.96ms: NoMethodError (undefined method `type=' for #<Pay::PaymentMethod id: nil, customer_id: 4, processor_id: "pm_1L8S8LFrvo3SEsBqvUo8xcpQ", default: nil, payment_type: nil, data: nil, created_at: nil, updated_at: nil>):

----
I am using:

- Pay 4.0.0
- Stripe 6.2.0

----

**Relevant Webhook Event Logs**

| Date | Stripe Listen Log |
| ----------- | ----------- |
| 2022-06-08 11:53:34   | --> payment_method.attached [evt_1L8S8QFrvo3SEsBqhr2j6r3Y] |
|2022-06-08 11:53:34  | <-- [200] POST http://localhost:3000/pay/webhooks/stripe [evt_1L8S8QFrvo3SEsBqhr2j6r3Y] |

**Relevant Docker Logs**

|  Log |
| ----------- |
| [ActiveJob] [Pay::Webhooks::ProcessJob] [757d6b3a-d5d8-4d48-8312-76e48a97eb63]   Pay::Webhook Load (0.7ms)  SELECT "pay_webhooks".* FROM "pay_webhooks" WHERE "pay_webhooks"."id" = $1 LIMIT $2  [["id", 74], ["LIMIT", 1]]
| [ActiveJob] [Pay::Webhooks::ProcessJob] [757d6b3a-d5d8-4d48-8312-76e48a97eb63] Performing Pay::Webhooks::ProcessJob (Job ID: 757d6b3a-d5d8-4d48-8312-76e48a97eb63) from Sidekiq(default) enqueued at 2022-06-08T16:53:34Z with arguments: #<GlobalID:0x000055b53a3c7108 @uri=#<URI::GID gid://account-manager/Pay::Webhook/74>>
 | 2022-06-08T16:53:34.392Z pid=1 tid=eex class=Pay::Webhooks::ProcessJob jid=2b6fc4dc9c03172470b9631f INFO: start
| [ActiveJob] [Pay::Webhooks::ProcessJob] [f88fd1ea-713a-45dd-8112-e01e419669c6]   Pay::Webhook Load (0.6ms)  SELECT "pay_webhooks".* FROM "pay_webhooks" WHERE "pay_webhooks"."id" = $1 LIMIT $2  [["id", 75], ["LIMIT", 1]]
 | [ActiveJob] [Pay::Webhooks::ProcessJob] [f88fd1ea-713a-45dd-8112-e01e419669c6] Performing Pay::Webhooks::ProcessJob (Job ID: f88fd1ea-713a-45dd-8112-e01e419669c6) from Sidekiq(default) enqueued at 2022-06-08T16:53:34Z with arguments: #<GlobalID:0x00007f9e788c6dd8 @uri=#<URI::GID gid://account-manager/Pay::Webhook/75>>
| [ActiveJob] [Pay::Webhooks::ProcessJob] [f88fd1ea-713a-45dd-8112-e01e419669c6]   Pay::Customer Load (0.7ms)  SELECT "pay_customers".* FROM "pay_customers" WHERE "pay_customers"."processor" = $1 AND "pay_customers"."processor_id" = $2 LIMIT $3  [["processor", "stripe"], ["processor_id", "cus_Lpo92KIuP8YtGy"], ["LIMIT", 1]]
| [ActiveJob] [Pay::Webhooks::ProcessJob] [f88fd1ea-713a-45dd-8112-e01e419669c6]   Pay::PaymentMethod Load (0.8ms)  SELECT "pay_payment_methods".* FROM "pay_payment_methods" WHERE "pay_payment_methods"."customer_id" = $1 AND "pay_payment_methods"."processor_id" = $2 ORDER BY "pay_payment_methods"."id" ASC LIMIT $3  [["customer_id", 4], ["processor_id", "pm_1L8S8LFrvo3SEsBqvUo8xcpQ"], ["LIMIT", 1]]
[ActiveJob] [Pay::Webhooks::ProcessJob] [f88fd1ea-713a-45dd-8112-e01e419669c6] Error performing Pay::Webhooks::ProcessJob (Job ID: f88fd1ea-713a-45dd-8112-e01e419669c6) from Sidekiq(default) in 96.96ms: NoMethodError (undefined method `type=' for #<Pay::PaymentMethod id: nil, customer_id: 4, processor_id: "pm_1L8S8LFrvo3SEsBqvUo8xcpQ", default: nil, payment_type: nil, data: nil, created_at: nil, updated_at: nil>):
SEE STACK TRACE

**Stack trace of Error**

| Log | 
| ---- |
/usr/local/rvm/gems/ruby-3.0.3/gems/activemodel-7.0.2.2/lib/active_model/attribute_methods.rb:458:in `method_missing'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activemodel-7.0.2.2/lib/active_model/attribute_methods.rb:211:in `type='
 /usr/local/rvm/gems/ruby-3.0.3/gems/activemodel-7.0.2.2/lib/active_model/attribute_assignment.rb:49:in `public_send'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activemodel-7.0.2.2/lib/active_model/attribute_assignment.rb:49:in `_assign_attribute'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activerecord-7.0.2.2/lib/active_record/attribute_assignment.rb:21:in `block in _assign_attributes'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activerecord-7.0.2.2/lib/active_record/attribute_assignment.rb:13:in `each'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activerecord-7.0.2.2/lib/active_record/attribute_assignment.rb:13:in `_assign_attributes'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activemodel-7.0.2.2/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activerecord-7.0.2.2/lib/active_record/persistence.rb:780:in `block in update!'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activerecord-7.0.2.2/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activerecord-7.0.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activerecord-7.0.2.2/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activerecord-7.0.2.2/lib/active_record/persistence.rb:779:in `update!'
 **[/usr/local/rvm/gems/ruby-3.0.3/gems/pay-4.0.0/lib/pay/stripe/billable.rb:159](https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/billable.rb#L159):in `save_payment_method'**
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/core_ext/module/delegation.rb:304:in `public_send'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/core_ext/module/delegation.rb:304:in `method_missing'
 **[/usr/local/rvm/gems/ruby-3.0.3/gems/pay-4.0.0/lib/pay/stripe/webhooks/payment_method_attached.rb:10](https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/webhooks/payment_method_attached.rb#L10):in `call'**
 **[/usr/local/rvm/gems/ruby-3.0.3/gems/pay-4.0.0/lib/pay/webhooks/delegator.rb:50](https://github.com/pay-rails/pay/blob/master/lib/pay/webhooks/delegator.rb#L50):in `call'**
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications/fanout.rb:236:in `finish'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications/fanout.rb:76:in `block in finish'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications/fanout.rb:91:in `block in iterate_guarding_exceptions'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications/fanout.rb:90:in `each'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications/fanout.rb:90:in `iterate_guarding_exceptions'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications/fanout.rb:76:in `finish'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications/instrumenter.rb:49:in `finish_with_state'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications/instrumenter.rb:30:in `instrument'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications.rb:206:in `instrument'
 **[/usr/local/rvm/gems/ruby-3.0.3/gems/pay-4.0.0/lib/pay/webhooks/delegator.rb:35](https://github.com/pay-rails/pay/blob/master/lib/pay/webhooks/delegator.rb#L35):in `instrument'**
 **[/usr/local/rvm/gems/ruby-3.0.3/gems/pay-4.0.0/lib/pay/webhooks.rb:7](https://github.com/pay-rails/pay/blob/master/lib/pay/webhooks.rb#L7):in `instrument'**
 **[/usr/local/rvm/gems/ruby-3.0.3/gems/pay-4.0.0/app/models/pay/webhook.rb:8](https://github.com/pay-rails/pay/blob/master/app/models/pay/webhook.rb#L8):in `process!'**
 **[/usr/local/rvm/gems/ruby-3.0.3/gems/pay-4.0.0/lib/pay/webhooks/process_job.rb:5](https://github.com/pay-rails/pay/blob/master/lib/pay/webhooks/process_job.rb#L5):in `perform'**
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/execution.rb:59:in `block in _perform_job'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
 /usr/local/rvm/gems/ruby-3.0.3/gems/i18n-1.10.0/lib/i18n.rb:328:in `with_locale'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/callbacks.rb:127:in `instance_exec'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/callbacks.rb:127:in `instance_exec'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/callbacks.rb:138:in `run_callbacks'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/execution.rb:58:in `_perform_job'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/instrumentation.rb:20:in `_perform_job'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/execution.rb:46:in `perform_now'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/instrumentation.rb:14:in `block in perform_now'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/instrumentation.rb:25:in `block in instrument'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications.rb:206:in `block in instrument'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/notifications.rb:206:in `instrument'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/instrumentation.rb:35:in `instrument'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/instrumentation.rb:14:in `perform_now'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/logging.rb:18:in `block in perform_now'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/tagged_logging.rb:99:in `block in tagged'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/tagged_logging.rb:37:in `tagged'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/tagged_logging.rb:99:in `tagged'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/logging.rb:25:in `tag_logger'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/logging.rb:18:in `perform_now'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/execution.rb:24:in `block in execute'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/execution_wrapper.rb:92:in `wrap'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/reloader.rb:72:in `block in wrap'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/reloader.rb:71:in `wrap'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/callbacks.rb:127:in `instance_exec'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/callbacks.rb:138:in `run_callbacks'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/execution.rb:22:in `execute'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activejob-7.0.2.2/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:196:in `execute_job'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:163:in `block in process'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:114:in `local'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/rails.rb:14:in `block in call'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/execution_wrapper.rb:92:in `wrap'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/reloader.rb:72:in `block in wrap'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/execution_wrapper.rb:92:in `wrap'
 /usr/local/rvm/gems/ruby-3.0.3/gems/activesupport-7.0.2.2/lib/active_support/reloader.rb:71:in `wrap'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/rails.rb:13:in `call'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:257:in `stats'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:13:in `call'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:81:in `global'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:39:in `prepare'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:123:in `dispatch'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:162:in `process'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:78:in `process_one'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:68:in `run'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:56:in `watchdog'
 /usr/local/rvm/gems/ruby-3.0.3/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:65:in `block in safe_thread'

**Comment by alexanderdavisn** [comment]
Ah. Yeah. That was the problem. Now that I have reverted that back to type, I have this error showing up:

>ArgumentError: Rails couldn't find a valid model for PaymentMethod association. Please provide the :class_name option on the association declaration. If :class_name is already provided, make sure it's an ActiveRecord::Base subclass.

It can be traced back to:
> [/usr/local/rvm/gems/ruby-3.0.3/gems/pay-4.0.0/lib/pay/stripe/billable.rb:153](https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/billable.rb#L153):in `save_payment_method'

Do I need to change the default way relationships are configured?

**Comment by alexanderdavisn** [comment]
I had to add the associations between PayCustoemr and PayPaymentMethod to my model and set the PayPaymentMethod inheritance column to nil and I got it to work.
