### ISSUE TITLE
Customer binding on checkout object not being respected and generating a DB error

### ISSUE THREAD

**Issue by dynelight** [pay-rails/pay#741]
Hello again. 

Im trying to set a `customer` on a checkout object, in order to tie several subscriptions to one customer ID. 

Example: 

```
checkout_object = {
          mode: checkout[:mode],
          line_items: checkout[:line_items],
          success_url: "#{root_url}entities",
          cancel_url: "#{root_url}entities/new",
          customer: get_current_group.stripe_id,
          client_reference_id: get_current_group.stripe_id
        }
        checkout_object.merge(
          subscription_data: {
            pay_name: "#{@entity.id} - #{@entity.name}" 
          }
        ) if checkout[:mode] == 'subscription'
        @checkout_session = @entity.payment_processor.checkout(checkout_object)
```

I'm finding two different things happen: 

1.) The first one is that even by passing a customer, a new customer is always generated on stripe for this entity

2.) Even though the payment is done and reflected on stripe, the callback is generating a duplicate MySQL entry: 

```
[ActiveJob] [Pay::Webhooks::ProcessJob] [f3c10e83-abc7-4f65-8d56-6d1b3fa2acce] Error performing Pay::Webhooks::ProcessJob (Job ID: f3c10e83-abc7-4f65-8d56-6d1b3fa2acce) from Async(default) in 2981.53ms: ActiveRecord::RecordNotUnique (Mysql2::Error: Duplicate entry '270-ch_2M8ck885cJoRoAtC1ldHentu' for key 'pay_charges.index_pay_charges_on_customer_id_and_processor_id'):
```

This is happening here: 

```
/Users/dynelight/.rvm/gems/ruby-2.7.5/gems/pay-5.0.4/lib/pay/stripe/charge.rb:95:in `sync'
/Users/dynelight/.rvm/gems/ruby-2.7.5/gems/pay-5.0.4/lib/pay/stripe/subscription.rb:87:in `sync'
/Users/dynelight/.rvm/gems/ruby-2.7.5/gems/pay-5.0.4/lib/pay/stripe/webhooks/checkout_session_completed.rb:18:in `call'
/Users/dynelight/.rvm/gems/ruby-2.7.5/gems/pay-5.0.4/lib/pay/webhooks/delegator.rb:50:in `call'
```

Any ideas why this might be happening? 

Really appreciate the feedback :)

**Comment by dynelight** [comment]
1.) I didn't have a Pay::Customer item created for this entity. So even though the `stripe_id` exists, since it's not on `Pay::Customer`, it ignored it and created a new customer

2.) Somehow I didn't have the newest gem version. I updated it and it's all good now.
