### ISSUE TITLE
Undefined method `refunds' for Stripe Charge in webhooks process job

### ISSUE THREAD

**Issue by kaycbas** [pay-rails/pay#758]
I've installed pay and stripe gems and set up Stripe Checkout in my app. 
```
gem "pay", "~> 6.1.0"
gem "stripe", "~> 8.0.0"
```
After a user completes a purchase, I can see my Rails backend receive a webhook and a Sidekiq job is kicked off to process it, however the job fails with the error:
```
NoMethodError (undefined method `refunds' for #<Stripe::Charge:0x64dc id=ch_3MG3YjEdROyQ6Skl1ctjvN4M> JSON: {
  "id": "ch_3MG3YjEdROyQ6Skl1ctjvN4M",
  "object": "charge",
  "amount": 100,
  "amount_captured": 100,
  "amount_refunded": 0,
  "application": null,
  "application_fee": null,
  "application_fee_amount": null,
  "balance_transaction": "txn_3MG3YjEdROyQ6Skl1ltzFlz0",
  "billing_details": {"address":{"city":null,"country":"US","line1":null,"line2":null,"postal_code":"94123","state":null},"email":"new@gmail.com","name":"Kevin Bastoul","phone":null},
  "calculated_statement_descriptor": "SYNAPTIQ LEARNING INC",
  "captured": true,
  "created": 1671295706,
  "currency": "usd",
  "customer": "cus_N03VbMMywiebaw",
  "description": null,
  "destination": null,
  "dispute": null,
  "disputed": false,
  "failure_balance_transaction": null,
  "failure_code": null,
  "failure_message": null,
  "fraud_details": {},
  "invoice": null,
  "livemode": false,
  "metadata": {},
  "on_behalf_of": null,
  "order": null,
  "outcome": {"network_status":"approved_by_network","reason":null,"risk_level":"normal","risk_score":59,"seller_message":"Payment complete.","type":"authorized"},
  "paid": true,
  "payment_intent": "pi_3MG3YjEdROyQ6Skl1bDEKiZO",
  "payment_method": "pm_1MG3YjEdROyQ6SklzetRSPeF",
  "payment_method_details": {"card":{"brand":"visa","checks":{"address_line1_check":null,"address_postal_code_check":"pass","cvc_check":"pass"},"country":"US","exp_month":5,"exp_year":2026,"fingerprint":"xxKlgdvpeBMejDCH","funding":"credit","installments":null,"last4":"4242","mandate":null,"network":"visa","three_d_secure":null,"wallet":null},"type":"card"},
  "receipt_email": null,
  "receipt_number": null,
  "receipt_url": "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xS2J5S3FFZFJPeVE2U2tsKN3l95wGMga4fyTZ51Q6LBbOAtiaMRyu44yYI8zSi9DQsTf-S3nTzqCRKU-_SPLzVON1m2a_1XtGlYBC",
  "refunded": false,
  "review": null,
  "shipping": null,
  "source": null,
  "source_transfer": null,
  "statement_descriptor": null,
  "statement_descriptor_suffix": null,
  "status": "succeeded",
  "transfer_data": null,
  "transfer_group": null
}
Did you mean?  refunded):
/Users/kevinbastoul/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/stripe-8.0.0/lib/stripe/stripe_object.rb:399:in `method_missing'
/Users/kevinbastoul/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/pay-6.1.1/lib/pay/stripe/charge.rb:26:in `sync'
/Users/kevinbastoul/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/pay-6.1.1/lib/pay/stripe/webhooks/checkout_session_completed.rb:10:in `call'
/Users/kevinbastoul/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/pay-6.1.1/lib/pay/webhooks/delegator.rb:50:in `call'
...
```
I can see that Stripe Charge objects are [supposed to have a refunds attribute](https://stripe.com/docs/api/charges/object) and I can see that the code in this gem calling `refunds` is not new, so I'm confused why this is happening. Any help would be appreciated.

**Comment by excid3** [comment]
Which webhook is it?

**Comment by kaycbas** [comment]
This is what my Rails log looks like after completing a payment through Stripe checkout. I haven't set up any webhook handlers for Stripe events, so I assumed this was built into the Pay gem.
```
I, [2022-12-17T09:26:48.475701 #29067]  INFO -- : Started POST "/pay/webhooks/stripe" for 54.187.205.235 at 2022-12-17 09:26:48 -0800
I, [2022-12-17T09:26:48.476854 #29067]  INFO -- : Cannot render console from 54.187.205.235! Allowed networks: 127.0.0.0/127.255.255.255, ::1
I, [2022-12-17T09:26:48.615545 #29067]  INFO -- : Processing by Pay::Webhooks::StripeController#create as XML
I, [2022-12-17T09:26:48.615771 #29067]  INFO -- :   Parameters: {"id"=>"evt_1MG3CaEdROyQ6SklFlMAVx8t", "object"=>"event", "api_version"=>"2020-08-27", "created"=>1671294331, "data"=>{"object"=>{"id"=>"cs_test_a1lBJ08iRtiyAosJKitLhEzYPXEq5HRmnESLlcbzlTzJnHGILxCcAL50Im", "object"=>"checkout.session", "after_expiration"=>nil, "allow_promotion_codes"=>nil, "amount_subtotal"=>200, "amount_total"=>200, "automatic_tax"=>{"enabled"=>false, "status"=>nil}, "billing_address_collection"=>nil, "cancel_url"=>"http://localhost:3000?success=true&session_id={CHECKOUT_SESSION_ID}", "client_reference_id"=>nil, "consent"=>nil, "consent_collection"=>nil, "created"=>1671294308, "currency"=>"usd", "custom_text"=>{"shipping_address"=>nil, "submit"=>nil}, "customer"=>"cus_MziRYvn9FBzUrD", "customer_creation"=>nil, "customer_details"=>{"address"=>{"city"=>nil, "country"=>"US", "line1"=>nil, "line2"=>nil, "postal_code"=>"94123", "state"=>nil}, "email"=>"stripe@synaptiq.co", "name"=>"Kevin Bastoul", "phone"=>nil, "tax_exempt"=>"none", "tax_ids"=>[]}, "customer_email"=>nil, "expires_at"=>1671380707, "invoice"=>"in_1MG3CXEdROyQ6SklHEzopKvj", "invoice_creation"=>nil, "livemode"=>false, "locale"=>nil, "metadata"=>{}, "mode"=>"subscription", "payment_intent"=>nil, "payment_link"=>nil, "payment_method_collection"=>"always", "payment_method_options"=>nil, "payment_method_types"=>["card"], "payment_status"=>"paid", "phone_number_collection"=>{"enabled"=>false}, "recovered_from"=>nil, "setup_intent"=>nil, "shipping"=>nil, "shipping_address_collection"=>nil, "shipping_options"=>[], "shipping_rate"=>nil, "status"=>"complete", "submit_type"=>nil, "subscription"=>"sub_1MG3CXEdROyQ6SklWH8UEpv6", "success_url"=>"http://localhost:3000?canceled=true&session_id={CHECKOUT_SESSION_ID}", "total_details"=>{"amount_discount"=>0, "amount_shipping"=>0, "amount_tax"=>0}, "url"=>nil}}, "livemode"=>false, "pending_webhooks"=>2, "request"=>{"id"=>nil, "idempotency_key"=>nil}, "type"=>"checkout.session.completed", "stripe"=>{"id"=>"evt_1MG3CaEdROyQ6SklFlMAVx8t", "object"=>"event", "api_version"=>"2020-08-27", "created"=>1671294331, "data"=>{"object"=>{"id"=>"cs_test_a1lBJ08iRtiyAosJKitLhEzYPXEq5HRmnESLlcbzlTzJnHGILxCcAL50Im", "object"=>"checkout.session", "after_expiration"=>nil, "allow_promotion_codes"=>nil, "amount_subtotal"=>200, "amount_total"=>200, "automatic_tax"=>{"enabled"=>false, "status"=>nil}, "billing_address_collection"=>nil, "cancel_url"=>"http://localhost:3000?success=true&session_id={CHECKOUT_SESSION_ID}", "client_reference_id"=>nil, "consent"=>nil, "consent_collection"=>nil, "created"=>1671294308, "currency"=>"usd", "custom_text"=>{"shipping_address"=>nil, "submit"=>nil}, "customer"=>"cus_MziRYvn9FBzUrD", "customer_creation"=>nil, "customer_details"=>{"address"=>{"city"=>nil, "country"=>"US", "line1"=>nil, "line2"=>nil, "postal_code"=>"94123", "state"=>nil}, "email"=>"stripe@synaptiq.co", "name"=>"Kevin Bastoul", "phone"=>nil, "tax_exempt"=>"none", "tax_ids"=>[]}, "customer_email"=>nil, "expires_at"=>1671380707, "invoice"=>"in_1MG3CXEdROyQ6SklHEzopKvj", "invoice_creation"=>nil, "livemode"=>false, "locale"=>nil, "metadata"=>{}, "mode"=>"subscription", "payment_intent"=>nil, "payment_link"=>nil, "payment_method_collection"=>"always", "payment_method_options"=>nil, "payment_method_types"=>["card"], "payment_status"=>"paid", "phone_number_collection"=>{"enabled"=>false}, "recovered_from"=>nil, "setup_intent"=>nil, "shipping"=>nil, "shipping_address_collection"=>nil, "shipping_options"=>[], "shipping_rate"=>nil, "status"=>"complete", "submit_type"=>nil, "subscription"=>"sub_1MG3CXEdROyQ6SklWH8UEpv6", "success_url"=>"http://localhost:3000?canceled=true&session_id={CHECKOUT_SESSION_ID}", "total_details"=>{"amount_discount"=>0, "amount_shipping"=>0, "amount_tax"=>0}, "url"=>nil}}, "livemode"=>false, "pending_webhooks"=>2, "request"=>{"id"=>nil, "idempotency_key"=>nil}, "type"=>"checkout.session.completed"}}
```

**Comment by excid3** [comment]
Thanks. That's exactly what I needed. 👍

**Comment by excid3** [comment]
Alright, this should be fixed. Was trying to save an API request by expanding the payment intent's charge, but didn't expand the charge's details on top of that. 

Going back to the simplified version so we can let the Charge class manage the expands in one place.

**Comment by excid3** [comment]
Give master a try and let me know if that fixes it for you?

**Comment by kaycbas** [comment]
It worked! Thanks so much for responding and fixing that so quickly.

**Comment by excid3** [comment]
Awesome, will cut a new release for this.
