### ISSUE TITLE
NoMethodError (undefined method `processor' for nil:NilClass)

### ISSUE THREAD

**Issue by simonsapiel** [pay-rails/pay#759]
Running into some odd error when trying to create a subscription. The controller method is as follows
```ruby
def create
  @checkout_session = current_user.payment_processor.checkout(
      mode: "subscription",
      line_items: "price_1Kd9RTJyJZSBS78UdXTYcdSb",
      locale: 'en',
      allow_promotion_codes: true,
      subscription_data: {
        trial_period_days: 14
      },
      success_url: root_url,
      cancel_url: root_url  
    )
  redirect_to @checkout_session.url, allow_other_host: true, status: :see_other
end
```
and the error I'm running into is the following
```
Error performing Pay::Webhooks::ProcessJob (Job ID: 7b5203eb-aa5b-437c-be3d-89e884306ccb) from Async(default) in 259.65ms: NoMethodError (undefined method `processor' for nil:NilClass
2022-12-18T16:31:46.027317+00:00 app[web.1]: 
2022-12-18T16:31:46.027318+00:00 app[web.1]:       @payment_processor ||= self.class.pay_processor_for(customer.processor).new(self)
2022-12-18T16:31:46.027319+00:00 app[web.1]:                                                                   ^^^^^^^^^^):
```
it would seem like the customer object is nil here? Has there been some major updates to the way checkouts/subscriptions are created which I should be aware of?

**Comment by excid3** [comment]
Can you provide the full stack trace?

**Comment by simonsapiel** [comment]
@excid3 Sure here it is
```
ERROR -- : [ActiveJob] [Pay::Webhooks::ProcessJob] [7b5203eb-aa5b-437c-be3d-89e884306ccb] Error performing Pay::Webhooks::ProcessJob (Job ID: 7b5203eb-aa5b-437c-be3d-89e884306ccb) from Async(default) in 259.65ms: NoMethodError (undefined method `processor' for nil:NilClass
2022-12-18T16:31:46.027317+00:00 app[web.1]: 
2022-12-18T16:31:46.027318+00:00 app[web.1]:       @payment_processor ||= self.class.pay_processor_for(customer.processor).new(self)
2022-12-18T16:31:46.027319+00:00 app[web.1]:                                                                   ^^^^^^^^^^):
2022-12-18T16:31:46.027320+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/pay-6.1.0/app/models/pay/subscription.rb:61:in `payment_processor'
2022-12-18T16:31:46.027332+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/core_ext/module/delegation.rb:299:in `respond_to_missing?'
2022-12-18T16:31:46.027333+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activemodel-7.0.3.1/lib/active_model/attribute_methods.rb:477:in `respond_to?'
2022-12-18T16:31:46.027333+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activemodel-7.0.3.1/lib/active_model/attribute_methods.rb:477:in `respond_to?'
2022-12-18T16:31:46.027333+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/attribute_methods.rb:208:in `respond_to?'
2022-12-18T16:31:46.027334+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activemodel-7.0.3.1/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
2022-12-18T16:31:46.027334+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/attribute_assignment.rb:21:in `block in _assign_attributes'
2022-12-18T16:31:46.027334+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/attribute_assignment.rb:13:in `each'
2022-12-18T16:31:46.027335+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/attribute_assignment.rb:13:in `_assign_attributes'
2022-12-18T16:31:46.027341+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activemodel-7.0.3.1/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
2022-12-18T16:31:46.027341+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/core.rb:468:in `initialize'
2022-12-18T16:31:46.027341+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/inheritance.rb:75:in `new'
2022-12-18T16:31:46.027341+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/inheritance.rb:75:in `new'
2022-12-18T16:31:46.027342+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/reflection.rb:158:in `build_association'
2022-12-18T16:31:46.027342+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/associations/association.rb:337:in `build_record'
2022-12-18T16:31:46.027342+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/associations/collection_association.rb:349:in `_create_record'
2022-12-18T16:31:46.027343+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/associations/has_many_association.rb:137:in `_create_record'
2022-12-18T16:31:46.027343+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/associations/association.rb:208:in `create!'
2022-12-18T16:31:46.027343+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/associations/collection_proxy.rb:364:in `create!'
2022-12-18T16:31:46.027344+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/pay-6.1.0/lib/pay/stripe/subscription.rb:98:in `sync'
2022-12-18T16:31:46.027344+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/pay-6.1.0/lib/pay/stripe/webhooks/subscription_created.rb:6:in `call'
2022-12-18T16:31:46.027344+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/pay-6.1.0/lib/pay/webhooks/delegator.rb:50:in `call'
2022-12-18T16:31:46.027344+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications/fanout.rb:236:in `finish'
2022-12-18T16:31:46.027345+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications/fanout.rb:76:in `block in finish'
2022-12-18T16:31:46.027345+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications/fanout.rb:91:in `block in iterate_guarding_exceptions'
2022-12-18T16:31:46.027345+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications/fanout.rb:90:in `each'
2022-12-18T16:31:46.027346+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications/fanout.rb:90:in `iterate_guarding_exceptions'
2022-12-18T16:31:46.027346+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications/fanout.rb:76:in `finish'
2022-12-18T16:31:46.027346+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications/instrumenter.rb:49:in `finish_with_state'
2022-12-18T16:31:46.027346+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications/instrumenter.rb:30:in `instrument'
2022-12-18T16:31:46.027350+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications.rb:206:in `instrument'
2022-12-18T16:31:46.027350+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/pay-6.1.0/lib/pay/webhooks/delegator.rb:35:in `instrument'
2022-12-18T16:31:46.027350+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/pay-6.1.0/lib/pay/webhooks.rb:7:in `instrument'
2022-12-18T16:31:46.027350+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/pay-6.1.0/app/models/pay/webhook.rb:8:in `process!'
2022-12-18T16:31:46.027351+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/pay-6.1.0/lib/pay/webhooks/process_job.rb:5:in `perform'
2022-12-18T16:31:46.027351+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/execution.rb:59:in `block in _perform_job'
2022-12-18T16:31:46.027351+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
2022-12-18T16:31:46.027351+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
2022-12-18T16:31:46.027352+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
2022-12-18T16:31:46.027352+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/callbacks.rb:127:in `instance_exec'
2022-12-18T16:31:46.027352+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
2022-12-18T16:31:46.027352+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
2022-12-18T16:31:46.027353+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
2022-12-18T16:31:46.027353+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/callbacks.rb:127:in `instance_exec'
2022-12-18T16:31:46.027353+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
2022-12-18T16:31:46.027353+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/callbacks.rb:138:in `run_callbacks'
2022-12-18T16:31:46.027354+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/execution.rb:58:in `_perform_job'
2022-12-18T16:31:46.027354+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/instrumentation.rb:20:in `_perform_job'
2022-12-18T16:31:46.027354+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/execution.rb:46:in `perform_now'
2022-12-18T16:31:46.027355+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/instrumentation.rb:14:in `block in perform_now'
2022-12-18T16:31:46.027355+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/instrumentation.rb:25:in `block in instrument'
2022-12-18T16:31:46.027355+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications.rb:206:in `block in instrument'
2022-12-18T16:31:46.027355+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2022-12-18T16:31:46.027356+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/notifications.rb:206:in `instrument'
2022-12-18T16:31:46.027356+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/instrumentation.rb:35:in `instrument'
2022-12-18T16:31:46.027356+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/instrumentation.rb:14:in `perform_now'
2022-12-18T16:31:46.027356+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/logging.rb:18:in `block in perform_now'
2022-12-18T16:31:46.027356+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/tagged_logging.rb:114:in `block in tagged'
2022-12-18T16:31:46.027357+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/tagged_logging.rb:38:in `tagged'
2022-12-18T16:31:46.027357+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/tagged_logging.rb:114:in `tagged'
2022-12-18T16:31:46.027357+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/logging.rb:25:in `tag_logger'
2022-12-18T16:31:46.027357+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/logging.rb:18:in `perform_now'
2022-12-18T16:31:46.027357+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/execution.rb:24:in `block in execute'
2022-12-18T16:31:46.027358+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
2022-12-18T16:31:46.027358+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
2022-12-18T16:31:46.027358+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/execution_wrapper.rb:92:in `wrap'
2022-12-18T16:31:46.027358+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
2022-12-18T16:31:46.027361+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/execution_wrapper.rb:92:in `wrap'
2022-12-18T16:31:46.027361+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/reloader.rb:71:in `wrap'
2022-12-18T16:31:46.027361+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
2022-12-18T16:31:46.027361+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/callbacks.rb:127:in `instance_exec'
2022-12-18T16:31:46.027361+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
2022-12-18T16:31:46.027367+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/callbacks.rb:138:in `run_callbacks'
2022-12-18T16:31:46.027367+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/execution.rb:22:in `execute'
2022-12-18T16:31:46.027368+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/activejob-7.0.3.1/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
2022-12-18T16:31:46.027368+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
2022-12-18T16:31:46.027368+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
2022-12-18T16:31:46.027369+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
2022-12-18T16:31:46.027369+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
2022-12-18T16:31:46.027369+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
2022-12-18T16:31:46.027369+00:00 app[web.1]: /app/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```

**Comment by excid3** [comment]
Did you upgrade recently from v5? If so, have you run the migration for v6? https://github.com/pay-rails/pay/blob/master/UPGRADE.md#pay-50-to-60

It seems like it's hitting the `delegate_missing_to`, which would mean your database table probably isn't up-to-date with the new columns we added.
