### ISSUE TITLE
Issue running tests from master, Pay::Subscription::BraintreeTest#test_resume_on_grace_period:

### ISSUE THREAD

**Issue by jean-francois-labbe** [pay-rails/pay#90]
Hello,

I'm facing the following issue when running tests from master 976cbad.

The error is visible here https://travis-ci.org/jean-francois-labbe/pay/jobs/588079100

```
Error:
Pay::Subscription::BraintreeTest#test_resume_on_grace_period:
VCR::Errors::UnhandledHTTPRequestError: 

================================================================================

An HTTP request has been made that VCR does not know how to handle:
  PUT https://api.sandbox.braintreegateway.com/merchants/zyfwpztymjqdcc5g/subscriptions/47grp2

VCR is currently using the following cassette:
  - /home/travis/build/jean-francois-labbe/pay/test/vcr_cassettes/braintree-resume.yml
    - :record => :once
    - :match_requests_on => [:method, :uri]

Under the current configuration VCR can not find a suitable HTTP interaction
to replay and is prevented from recording new requests. There are a few ways
you can deal with this:

  * If you're surprised VCR is raising this error
    and want insight about how VCR attempted to handle the request,
    you can use the debug_logger configuration option to log more details [1].

  * You can use the :new_episodes record mode to allow VCR to
    record this new request to the existing cassette [2].

  * If you want VCR to ignore this request (and others like it), you can
    set an `ignore_request` callback [3].
  * The current record mode (:once) does not allow new requests to be recorded
    to a previously recorded cassette. You can delete the cassette file and re-run
    your tests to allow the cassette to be recorded with this request [4].

  * The cassette contains 4 HTTP interactions that have not been
    played back. If your request is non-deterministic, you may need to
    change your :match_requests_on cassette option to be more lenient
    or use a custom request matcher to allow it to match [5].
[1] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/configuration/debug-logging
[2] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/record-modes/new-episodes
[3] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/configuration/ignore-request
[4] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/record-modes/once
[5] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/request-matching

================================================================================
    vcr (4.0.0) lib/vcr/request_handler.rb:97:in `on_unhandled_request'
    vcr (4.0.0) lib/vcr/library_hooks/webmock.rb:129:in `on_unhandled_request'
    vcr (4.0.0) lib/vcr/request_handler.rb:24:in `handle'
    vcr (4.0.0) lib/vcr/library_hooks/webmock.rb:144:in `block in <module:WebMock>'
    webmock (3.5.1) lib/webmock/stub_registry.rb:28:in `block in register_global_stub'
    webmock (3.5.1) lib/webmock/request_pattern.rb:40:in `matches?'
    webmock (3.5.1) lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
    webmock (3.5.1) lib/webmock/stub_registry.rb:57:in `each'
    webmock (3.5.1) lib/webmock/stub_registry.rb:57:in `detect'
    webmock (3.5.1) lib/webmock/stub_registry.rb:57:in `request_stub_for'
    webmock (3.5.1) lib/webmock/stub_registry.rb:50:in `response_for_request'
    webmock (3.5.1) lib/webmock/http_lib_adapters/net_http.rb:79:in `request'
    braintree (2.96.0) lib/braintree/http.rb:137:in `block in _http_do'
    webmock (3.5.1) lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
    webmock (3.5.1) lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
    braintree (2.96.0) lib/braintree/http.rb:109:in `_http_do'
    braintree (2.96.0) lib/braintree/http.rb:46:in `put'
    braintree (2.96.0) lib/braintree/subscription_gateway.rb:59:in `update'
    /home/travis/build/jean-francois-labbe/pay/lib/pay/braintree/subscription.rb:15:in `braintree_cancel'
    /home/travis/build/jean-francois-labbe/pay/app/models/pay/subscription.rb:49:in `cancel'
    /home/travis/build/jean-francois-labbe/pay/test/models/braintree_test.rb:32:in `block (2 levels) in <class:BraintreeTest>'
    vcr (4.0.0) lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
    vcr (4.0.0) lib/vcr.rb:188:in `use_cassette'
    /home/travis/build/jean-francois-labbe/pay/test/models/braintree_test.rb:29:in `block in <class:BraintreeTest>'
    minitest (5.11.3) lib/minitest/test.rb:98:in `block (3 levels) in run'
    minitest (5.11.3) lib/minitest/test.rb:195:in `capture_exceptions'
    minitest (5.11.3) lib/minitest/test.rb:95:in `block (2 levels) in run'
    minitest (5.11.3) lib/minitest.rb:265:in `time_it'
    minitest (5.11.3) lib/minitest/test.rb:94:in `block in run'
    minitest (5.11.3) lib/minitest.rb:360:in `on_signal'
    minitest (5.11.3) lib/minitest/test.rb:211:in `with_info_handler'
    minitest (5.11.3) lib/minitest/test.rb:93:in `run'
    minitest (5.11.3) lib/minitest.rb:960:in `run_one_method'
    minitest (5.11.3) lib/minitest.rb:334:in `run_one_method'
    minitest (5.11.3) lib/minitest.rb:321:in `block (2 levels) in run'
    minitest (5.11.3) lib/minitest.rb:320:in `each'
    minitest (5.11.3) lib/minitest.rb:320:in `block in run'
    minitest (5.11.3) lib/minitest.rb:360:in `on_signal'
    minitest (5.11.3) lib/minitest.rb:347:in `with_info_handler'
    minitest (5.11.3) lib/minitest.rb:319:in `run'
    railties (5.2.3) lib/rails/test_unit/line_filtering.rb:10:in `run'
    minitest (5.11.3) lib/minitest.rb:159:in `block in __run'
    minitest (5.11.3) lib/minitest.rb:159:in `map'
    minitest (5.11.3) lib/minitest.rb:159:in `__run'
    minitest (5.11.3) lib/minitest.rb:136:in `run'
    minitest (5.11.3) lib/minitest.rb:63:in `block in autorun'
bin/rails test /home/travis/build/jean-francois-labbe/pay/test/models/braintree_test.rb:28
```

Does anyone know why?

**Comment by excid3** [comment]
For some reason, this specific test fails when we change gem versions I noticed. Not quite sure what is causing it.

**Comment by excid3** [comment]
Figured out the problem a while back and forgot to update this. Needed to `travel_to` the same time that the test was running with VCR so that it times matched up.
