### ISSUE TITLE
[BUG] Calling charge 

### ISSUE THREAD

**Issue by gs-deliverists-io** [pay-rails/pay#916]
## Bug Report

**Describe the Bug:**
After upgrade to pay-7.1.0 and stripe-10.2.0 with ruby-3.2.2 and Rails 7.1.2 I can't create a charge

**To Reproduce:**
irb(main):004> user.payment_processor.charge(1400)
  Pay::PaymentMethod Load (0.3ms)  SELECT `pay_payment_methods`.* FROM `pay_payment_methods` WHERE `pay_payment_methods`.`customer_id` = 5 AND `pay_payment_methods`.`default` = TRUE LIMIT 1
/Users/sfistak/code/deliverists.io/evetly/vendor/plugins/ruby/3.2.0/gems/activerecord-7.1.2/lib/active_record/attribute_methods/read.rb:51:in `_read_attribute': stack level too deep (SystemStackError)

**Expected Behavior:**
The charge should work

**Actual Behavior:**
`stack level too deep`  - exception.

**Screenshots (if applicable):**

**Environment:**
- Pay gem version: 
- Ruby version: 
- Rails version: 
- Operating System: 

**Additional Context:**

**Possible Fix:**

**Steps to Reproduce with Fix (if available):**

**Related Issues:**

**Labels to Apply:**

**Checklist:**

- [ ] I have searched for similar issues and couldn't find any
- [ ] I have checked the documentation for relevant information
- [ ] I have included all the required information

**Comment by deanpcmad** [comment]
Have you run through the [upgrade notes](https://github.com/pay-rails/pay/blob/main/UPGRADE.md#pay-60-to-pay-70)?

**Comment by gs-deliverists-io** [comment]
I followed the upgrade tutorial
```
Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
 (called from block (2 levels) in require at /Users/sfistak/.gem/ruby/3.2.2/gems/bundler-2.4.22/lib/bundler/runtime.rb:60)
== 20231207125841 UpgradeToPay7: migrating ====================================
== 20231207125841 UpgradeToPay7: migrated (0.0000s) ===========================

Model files unchanged.
evetly(main)>bin/rails c
/Users/sfistak/code/deliverists.io/evetly/vendor/plugins/ruby/3.2.0/gems/rack-3.0.8/lib/rack/file.rb:5: warning: Rack::File is deprecated and will be removed in Rack 3.1
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.

Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
 (called from block (2 levels) in require at /Users/sfistak/.gem/ruby/3.2.2/gems/bundler-2.4.22/lib/bundler/runtime.rb:60)
Loading development environment (Rails 7.1.2)
irb(main):001> Pay::Customer.find_each { |c| c.update(stripe_account: c.data&.dig("stripe_account")) }
  Pay::Customer Load (0.5ms)  SELECT `pay_customers`.* FROM `pay_customers` ORDER BY `pay_customers`.`id` ASC LIMIT 1000
/Users/sfistak/code/deliverists.io/evetly/vendor/plugins/ruby/3.2.0/gems/activemodel-7.1.2/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute': unknown attribute 'stripe_account' for Pay::Customer. (ActiveModel::UnknownAttributeError)

          raise UnknownAttributeError.new(self, k.to_s)
          ^^^^^
irb(main):002> Pay::Subscription.find_each { |c| c.update(stripe_account: c.data&.dig("stripe_account")) }
  Pay::Subscription Load (1.1ms)  SELECT `pay_subscriptions`.* FROM `pay_subscriptions` ORDER BY `pay_subscriptions`.`id` ASC LIMIT 1000
=> nil
irb(main):003> Pay::PaymentMethod.find_each { |c| c.update(stripe_account: c.data&.dig("stripe_account")) }
  Pay::PaymentMethod Load (0.7ms)  SELECT `pay_payment_methods`.* FROM `pay_payment_methods` ORDER BY `pay_payment_methods`.`id` ASC LIMIT 1000
/Users/sfistak/code/deliverists.io/evetly/vendor/plugins/ruby/3.2.0/gems/activemodel-7.1.2/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute': unknown attribute 'stripe_account' for Pay::PaymentMethod. (ActiveModel::UnknownAttributeError)

          raise UnknownAttributeError.new(self, k.to_s)
          ^^^^^
irb(main):004> Pay::Charge.find_each { |c| c.update(stripe_account: c.data&.dig("stripe_account")) }
  Pay::Charge Load (0.9ms)  SELECT `pay_charges`.* FROM `pay_charges` ORDER BY `pay_charges`.`id` ASC LIMIT 1000
/Users/sfistak/code/deliverists.io/evetly/vendor/plugins/ruby/3.2.0/gems/activemodel-7.1.2/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute': unknown attribute 'stripe_account' for Pay::Charge. (ActiveModel::UnknownAttributeError)

          raise UnknownAttributeError.new(self, k.to_s)
          ^^^^^
irb(main):005>
````

after that, still the error persists.

```
irb(main):002> user.payment_processor.charge(100)
  Pay::Customer Load (0.6ms)  SELECT `pay_customers`.* FROM `pay_customers` WHERE `pay_customers`.`owner_id` = 87 AND `pay_customers`.`owner_type` = 'User' AND `pay_customers`.`default` = TRUE AND `pay_customers`.`deleted_at` IS NULL LIMIT 1
  Pay::PaymentMethod Load (0.3ms)  SELECT `pay_payment_methods`.* FROM `pay_payment_methods` WHERE `pay_payment_methods`.`customer_id` = 5 AND `pay_payment_methods`.`default` = TRUE LIMIT 1
/Users/sfistak/code/deliverists.io/evetly/vendor/plugins/ruby/3.2.0/gems/activerecord-7.1.2/lib/active_record/attribute_methods/read.rb:51:in `_read_attribute': stack level too deep (SystemStackError)
irb(main):003>
```

**Comment by deanpcmad** [comment]
It's saying `unknown attribute 'stripe_account`. 🤔  Can you post your schema.rb, just your pay tables?

**Comment by gs-deliverists-io** [comment]
Ok! Got it!! @deanpcmad , I've just noticed that the migration file is empty ... after applying suggested `add_column`  all went fine.

The issue is fixed and the charge went smoothly.
